<?php
/**
 * CustomCredentialsType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Carbon
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * Carbon
 *
 * Connect external data to LLMs, no matter the source.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


namespace Carbon\Model;
use \Carbon\ObjectSerializer;

/**
 * CustomCredentialsType Class Doc Comment
 *
 * @category Class
 * @package  Carbon
 */
class CustomCredentialsType
{
    /**
     * Possible values of this enum
     */
    public const OPENAI = 'OPENAI';

    public const COHERE = 'COHERE';

    public const AZURE_OPENAI = 'AZURE_OPENAI';

    public const AZURE_OPENAI_V3 = 'AZURE_OPENAI_V3';

    public const UPSTAGE = 'UPSTAGE';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::OPENAI,
            self::COHERE,
            self::AZURE_OPENAI,
            self::AZURE_OPENAI_V3,
            self::UPSTAGE
        ];
    }
}


