<?php
/**
 * FileFormatsNullable
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Carbon
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * Carbon
 *
 * Connect external data to LLMs, no matter the source.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


namespace Carbon\Model;
use \Carbon\ObjectSerializer;

/**
 * FileFormatsNullable Class Doc Comment
 *
 * @category Class
 * @package  Carbon
 */
class FileFormatsNullable
{
    /**
     * Possible values of this enum
     */
    public const TXT = 'TXT';

    public const CSV = 'CSV';

    public const TSV = 'TSV';

    public const PDF = 'PDF';

    public const DOCX = 'DOCX';

    public const PPTX = 'PPTX';

    public const XLSX = 'XLSX';

    public const MD = 'MD';

    public const RTF = 'RTF';

    public const JSON = 'JSON';

    public const HTML = 'HTML';

    public const NOTION = 'NOTION';

    public const GOOGLE_DOCS = 'GOOGLE_DOCS';

    public const GOOGLE_SHEETS = 'GOOGLE_SHEETS';

    public const GOOGLE_SLIDES = 'GOOGLE_SLIDES';

    public const INTERCOM = 'INTERCOM';

    public const CONFLUENCE = 'CONFLUENCE';

    public const RSS_FEED = 'RSS_FEED';

    public const GMAIL = 'GMAIL';

    public const OUTLOOK = 'OUTLOOK';

    public const ZENDESK = 'ZENDESK';

    public const FRESHDESK = 'FRESHDESK';

    public const WEB_SCRAPE = 'WEB_SCRAPE';

    public const GITBOOK = 'GITBOOK';

    public const SALESFORCE = 'SALESFORCE';

    public const GITHUB = 'GITHUB';

    public const SLACK = 'SLACK';

    public const JPG = 'JPG';

    public const PNG = 'PNG';

    public const MP3 = 'MP3';

    public const MP2 = 'MP2';

    public const AAC = 'AAC';

    public const WAV = 'WAV';

    public const FLAC = 'FLAC';

    public const PCM = 'PCM';

    public const M4_A = 'M4A';

    public const OGG = 'OGG';

    public const OPUS = 'OPUS';

    public const MPEG = 'MPEG';

    public const MPG = 'MPG';

    public const MP4 = 'MP4';

    public const WMV = 'WMV';

    public const AVI = 'AVI';

    public const MOV = 'MOV';

    public const MKV = 'MKV';

    public const FLV = 'FLV';

    public const WEBM = 'WEBM';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::TXT,
            self::CSV,
            self::TSV,
            self::PDF,
            self::DOCX,
            self::PPTX,
            self::XLSX,
            self::MD,
            self::RTF,
            self::JSON,
            self::HTML,
            self::NOTION,
            self::GOOGLE_DOCS,
            self::GOOGLE_SHEETS,
            self::GOOGLE_SLIDES,
            self::INTERCOM,
            self::CONFLUENCE,
            self::RSS_FEED,
            self::GMAIL,
            self::OUTLOOK,
            self::ZENDESK,
            self::FRESHDESK,
            self::WEB_SCRAPE,
            self::GITBOOK,
            self::SALESFORCE,
            self::GITHUB,
            self::SLACK,
            self::JPG,
            self::PNG,
            self::MP3,
            self::MP2,
            self::AAC,
            self::WAV,
            self::FLAC,
            self::PCM,
            self::M4_A,
            self::OGG,
            self::OPUS,
            self::MPEG,
            self::MPG,
            self::MP4,
            self::WMV,
            self::AVI,
            self::MOV,
            self::MKV,
            self::FLV,
            self::WEBM
        ];
    }
}


