<?php
/**
 * FileStatus
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Carbon
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * Carbon
 *
 * Connect external data to LLMs, no matter the source.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


namespace Carbon\Model;
use \Carbon\ObjectSerializer;

/**
 * FileStatus Class Doc Comment
 *
 * @category Class
 * @package  Carbon
 */
class FileStatus
{
    /**
     * Possible values of this enum
     */
    public const ADDED = 'added';

    public const REMOVED = 'removed';

    public const MODIFIED = 'modified';

    public const RENAMED = 'renamed';

    public const COPIED = 'copied';

    public const CHANGED = 'changed';

    public const UNCHANGED = 'unchanged';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ADDED,
            self::REMOVED,
            self::MODIFIED,
            self::RENAMED,
            self::COPIED,
            self::CHANGED,
            self::UNCHANGED
        ];
    }
}


