<?php
/**
 * GongFileTypes
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Carbon
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * Carbon
 *
 * Connect external data to LLMs, no matter the source.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


namespace Carbon\Model;
use \Carbon\ObjectSerializer;

/**
 * GongFileTypes Class Doc Comment
 *
 * @category Class
 * @package  Carbon
 */
class GongFileTypes
{
    /**
     * Possible values of this enum
     */
    public const WORKSPACE = 'WORKSPACE';

    public const FOLDER = 'FOLDER';

    public const CALL = 'CALL';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::WORKSPACE,
            self::FOLDER,
            self::CALL
        ];
    }
}


