<?php
/**
 * IntercomFileTypes
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Carbon
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * Carbon
 *
 * Connect external data to LLMs, no matter the source.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


namespace Carbon\Model;
use \Carbon\ObjectSerializer;

/**
 * IntercomFileTypes Class Doc Comment
 *
 * @category Class
 * @package  Carbon
 */
class IntercomFileTypes
{
    /**
     * Possible values of this enum
     */
    public const ARTICLE = 'ARTICLE';

    public const COLLECTION = 'COLLECTION';

    public const HELP_CENTER = 'HELP_CENTER';

    public const TICKET = 'TICKET';

    public const TICKET_ATTACHMENT = 'TICKET_ATTACHMENT';

    public const CONTACT = 'CONTACT';

    public const ADMIN = 'ADMIN';

    public const TEAM = 'TEAM';

    public const CONVERSATION = 'CONVERSATION';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ARTICLE,
            self::COLLECTION,
            self::HELP_CENTER,
            self::TICKET,
            self::TICKET_ATTACHMENT,
            self::CONTACT,
            self::ADMIN,
            self::TEAM,
            self::CONVERSATION
        ];
    }
}


