<?php
/**
 * SimpleOAuthDataSources
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Carbon
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * Carbon
 *
 * Connect external data to LLMs, no matter the source.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


namespace Carbon\Model;
use \Carbon\ObjectSerializer;

/**
 * SimpleOAuthDataSources Class Doc Comment
 *
 * @category Class
 * @package  Carbon
 */
class SimpleOAuthDataSources
{
    /**
     * Possible values of this enum
     */
    public const GOOGLE_DRIVE = 'GOOGLE_DRIVE';

    public const INTERCOM = 'INTERCOM';

    public const DROPBOX = 'DROPBOX';

    public const ONEDRIVE = 'ONEDRIVE';

    public const BOX = 'BOX';

    public const GMAIL = 'GMAIL';

    public const OUTLOOK = 'OUTLOOK';

    public const SLACK = 'SLACK';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::GOOGLE_DRIVE,
            self::INTERCOM,
            self::DROPBOX,
            self::ONEDRIVE,
            self::BOX,
            self::GMAIL,
            self::OUTLOOK,
            self::SLACK
        ];
    }
}


