<?php
/**
 * AutoSyncEnabledSourcesPropertyTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Carbon
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * Carbon
 *
 * Connect external data to LLMs, no matter the source.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


namespace Carbon\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AutoSyncEnabledSourcesPropertyTest Class Doc Comment
 *
 * @category    Class
 * @description List of data source types to enable auto sync for. Empty array will remove all sources          and the string \&quot;ALL\&quot; will enable it for all data sources
 * @package     Carbon
 */
class AutoSyncEnabledSourcesPropertyTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AutoSyncEnabledSourcesProperty"
     */
    public function testAutoSyncEnabledSourcesProperty()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
