<?php
/**
 * DataSourceConfigurationTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Carbon
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * Carbon
 *
 * Connect external data to LLMs, no matter the source.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


namespace Carbon\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * DataSourceConfigurationTest Class Doc Comment
 *
 * @category    Class
 * @description DataSourceConfiguration
 * @package     Carbon
 */
class DataSourceConfigurationTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DataSourceConfiguration"
     */
    public function testDataSourceConfiguration()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "allowed_file_formats"
     */
    public function testPropertyAllowedFileFormats()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "google_workspace_docs_save_as"
     */
    public function testPropertyGoogleWorkspaceDocsSaveAs()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
