<?php
/**
 * DeleteFilesV2QueryInputTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Carbon
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * Carbon
 *
 * Connect external data to LLMs, no matter the source.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


namespace Carbon\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * DeleteFilesV2QueryInputTest Class Doc Comment
 *
 * @category    Class
 * @description DeleteFilesV2QueryInput
 * @package     Carbon
 */
class DeleteFilesV2QueryInputTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DeleteFilesV2QueryInput"
     */
    public function testDeleteFilesV2QueryInput()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "filters"
     */
    public function testPropertyFilters()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "send_webhook"
     */
    public function testPropertySendWebhook()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
