<?php
/**
 * HelpdeskFileSyncConfigTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Carbon
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * Carbon
 *
 * Connect external data to LLMs, no matter the source.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


namespace Carbon\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * HelpdeskFileSyncConfigTest Class Doc Comment
 *
 * @category    Class
 * @description HelpdeskFileSyncConfig
 * @package     Carbon
 */
class HelpdeskFileSyncConfigTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "HelpdeskFileSyncConfig"
     */
    public function testHelpdeskFileSyncConfig()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "file_types"
     */
    public function testPropertyFileTypes()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sync_attachments"
     */
    public function testPropertySyncAttachments()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
