<?php
/**
 * ModifyColdStorageParametersQueryInputTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Carbon
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * Carbon
 *
 * Connect external data to LLMs, no matter the source.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


namespace Carbon\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ModifyColdStorageParametersQueryInputTest Class Doc Comment
 *
 * @category    Class
 * @description ModifyColdStorageParametersQueryInput
 * @package     Carbon
 */
class ModifyColdStorageParametersQueryInputTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ModifyColdStorageParametersQueryInput"
     */
    public function testModifyColdStorageParametersQueryInput()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "filters"
     */
    public function testPropertyFilters()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "enable_cold_storage"
     */
    public function testPropertyEnableColdStorage()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "hot_storage_time_to_live"
     */
    public function testPropertyHotStorageTimeToLive()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
