<?php
/**
 * ParsedTextFormatsNullableTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Carbon
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * Carbon
 *
 * Connect external data to LLMs, no matter the source.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


namespace Carbon\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ParsedTextFormatsNullableTest Class Doc Comment
 *
 * @category    Class
 * @description The format in which the text content of the file should be parsed. Notion files are the only files         that support this feature. The default parsed text format is plain text.
 * @package     Carbon
 */
class ParsedTextFormatsNullableTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ParsedTextFormatsNullable"
     */
    public function testParsedTextFormatsNullable()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
