<?php
/**
 * CRMApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Carbon
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * Carbon
 *
 * Connect external data to LLMs, no matter the source.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


namespace Carbon\Test\Api;

use \Carbon\Configuration;
use \Carbon\ApiException;
use \Carbon\ObjectSerializer;
use PHPUnit\Framework\TestCase;

class CRMApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getAccount
     *
     * Get Account.
     *
     */
    public function testGetAccount()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAccounts
     *
     * Get Accounts.
     *
     */
    public function testGetAccounts()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getContact
     *
     * Get Contact.
     *
     */
    public function testGetContact()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getContacts
     *
     * Get Contacts.
     *
     */
    public function testGetContacts()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getLead
     *
     * Get Lead.
     *
     */
    public function testGetLead()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getLeads
     *
     * Get Leads.
     *
     */
    public function testGetLeads()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOpportunities
     *
     * Get Opportunities.
     *
     */
    public function testGetOpportunities()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOpportunity
     *
     * Get Opportunity.
     *
     */
    public function testGetOpportunity()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
