<?php
/**
 * GithubApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Carbon
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * Carbon
 *
 * Connect external data to LLMs, no matter the source.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


namespace Carbon\Test\Api;

use \Carbon\Configuration;
use \Carbon\ApiException;
use \Carbon\ObjectSerializer;
use PHPUnit\Framework\TestCase;

class GithubApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getIssue
     *
     * Issue.
     *
     */
    public function testGetIssue()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getIssues
     *
     * Issues.
     *
     */
    public function testGetIssues()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPr
     *
     * Get Pr.
     *
     */
    public function testGetPr()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPrComments
     *
     * Pr Comments.
     *
     */
    public function testGetPrComments()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPrCommits
     *
     * Pr Commits.
     *
     */
    public function testGetPrCommits()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPrFiles
     *
     * Pr Files.
     *
     */
    public function testGetPrFiles()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPullRequests
     *
     * Get Prs.
     *
     */
    public function testGetPullRequests()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
